import './globals.css';
import 'photoswipe/style.css';
import React from 'react';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-neutral-900 antialiased">{children}</body>
    </html>
  );
}
